### PR TITLE
Asc parse

### PR DESCRIPTION
**Pull request by aethernaught**
Hi
I added a simple parser for ascii asc DEMs

### CODE REVIEW

**Comment by pmcmonagle** [comment]
Cool, thanks for your contribution!

Where can I find some sample ASC format DEM files to test this with?
Also, is there a written spec for this format available anywhere?

**Comment by aethernaught** [comment]
Those are both good questions!   I'll get back to you with more info.

**Comment by aethernaught** [comment]
It is the ESRI Grid format, specfifically the open ASCII one: http://en.wikipedia.org/wiki/Esri_grid

You can convert other DEM formats to it easily using gdal_translate:
gdal_translate -of AAIGrid some_test.dem some_test.asc

As it is an ESRI format, you can presumably also save it as an output from ArcGIS

I don't have a small DEM available, but you can download DEMs of the right format from Koordinates, eg:  https://koordinates.com/layer/2138-wellington-city-1m-digital-elevation-model/

**Comment by pmcmonagle** [comment]
Is leading white-space part of the spec?

The example on the wiki breaks on demparser.py:99 due to lack of leading whitespace on each line. Without that whitespace, all of the values on the left-edge get mangled and single-digit values become empty strings which throws an exception on float('').

Other than that, everything checks out.

**Comment by aethernaught** [comment]
Sorry about the delay.  

I'm not sure if the leading space is part of the spec or not, it does appear in the output of gdal_translate but isn't on the wikipedia example.  I made a change to the asc parsing to be more robust and to succeed in both cases.

**Comment by pmcmonagle** [comment]
Perfect!
No need to apologize; it's not like there are deadlines on open source contributions. :)

Thank you for your contribution.

**Pull request merged**
